name: compvisionW2024
channels:
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - pip
  - pip:
    - numpy==1.26.4
    - scikit-image==0.23.2
    - scikit-learn==1.5.0
    - pandas==2.2.2
    - wget==3.2
    - matplotlib==3.8.4
    - seaborn==0.13.2
    - scipy==1.13.1
    - opencv-python==4.10.0.84
    - tqdm==4.66.4
    - imutils==0.5.4
    - ipywidgets==8.1.5
    - albumentations==1.4.10
    - pillow==10.3.0